#!/usr/bin/env python3
"""
Script to fetch 1000 high-quality kernel cases from multiple sources.
"""
import os
import sys
import django
import time
from typing import List, Dict

# Set up Django environment
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'kernel_cases.settings')
django.setup()

# Now we can import Django models and other components
from cases.acquisition.main import CaseAcquisition
from cases.models import KernelCase

# Extended keywords for better coverage
extended_keywords = [
    # English keywords
    "kernel panic",
    "kernel oops",
    "kernel deadlock",
    "kernel null pointer dereference",
    "kernel OOM",
    "kernel page allocation failure",
    "kernel memory leak",
    "kernel module error",
    "kernel driver failure",
    "kernel network issue",
    "kernel interrupt problem",
    "kernel scheduler issue",
    "kernel filesystem error",
    "kernel deadlock detection",
    "kernel soft lockup",
    "kernel hard lockup",
    "kernel RCU issue",
    "kernel crash analysis",
    "kernel stack trace",
    "kernel debugging",
    "kernel parameter tuning",
    "kernel patch analysis",
    "kernel performance issue",
    "kernel race condition",
    "kernel deadlock resolution",
    "kernel memory corruption",
    "kernel page fault",
    "kernel syscall error",
    "kernel panic troubleshooting",
    "kernel oops debugging",
    "kernel deadlock prevention",
    "kernel OOM debugging",
    "kernel memory management",
    "kernel thread issue",
    "kernel synchronization problem",
    "kernel signal handling",
    "kernel timekeeping issue",
    "kernel timer problem",
    "kernel CPU affinity issue",
    "kernel NUMA issue",
    "kernel PCI issue",
    "kernel USB issue",
    "kernel block device issue",
    "kernel network stack issue",
    "kernel socket issue",
    "kernel TCP/IP issue",
    "kernel filesystem corruption",
    "kernel ext4 issue",
    "kernel XFS issue",
    "kernel Btrfs issue",
    "kernel NFS issue",
    "kernel CIFS issue",
    "kernel virtualization issue",
    "kernel KVM issue",
    "kernel QEMU issue",
    "kernel container issue",
    "kernel Docker issue",
    "kernel Kubernetes issue",
    "kernel cgroup issue",
    "kernel namespace issue",
    "kernel security issue",
    "kernel SELinux issue",
    "kernel AppArmor issue",
    "kernel CAP_SYS_ADMIN issue",
    "kernel sysctl issue",
    "kernel boot issue",
    "kernel shutdown issue",
    "kernel suspend/resume issue",
    "kernel hibernation issue",
    "kernel power management issue",
    "kernel thermal issue",
    "kernel frequency scaling issue",
    "kernel ACPI issue",
    "kernel UEFI issue",
    "kernel firmware issue",
    "kernel module loading issue",
    "kernel module unloading issue",
    "kernel module dependency issue",
    "kernel symbol resolution issue",
    "kernel license issue",
    "kernel GPL issue",
    "kernel version mismatch",
    "kernel API change",
    "kernel ABI compatibility",
    "kernel backport issue",
    "kernel mainline issue",
    "kernel stable branch issue",
    "kernel longterm branch issue",
    "kernel regression",
    "kernel bisect",
    "kernel git issue",
    "kernel mail list issue",
    "kernel bug report",
    "kernel CVE fix",
    "kernel security patch",
    "kernel performance patch",
    "kernel feature implementation",
    "kernel driver development",
    "kernel module development",
    "kernel programming issue",
    "kernel C programming",
    "kernel assembly issue",
    "kernel debugfs",
    "kernel tracefs",
    "kernel ftrace",
    "kernel perf",
    "kernel BPF",
    "kernel eBPF",
    "kernel tracing issue",
    "kernel profiling issue",
    "kernel latency issue",
    "kernel realtime issue",
    "kernel RT patch",
    "kernel preempt issue",
    "kernel interrupt latency",
    "kernel spinlock issue",
    "kernel mutex issue",
    "kernel semaphore issue",
    "kernel rwlock issue",
    "kernel spinlock contention",
    "kernel mutex contention",
    "kernel memory barrier issue",
    "kernel cache coherence issue",
    "kernel TLB issue",
    "kernel page table issue",
    "kernel mmu issue",
    "kernel swap issue",
    "kernel zram issue",
    "kernel zswap issue",
    "kernel compaction issue",
    "kernel defragmentation issue",
    "kernel THP issue",
    "kernel hugepage issue",
    "kernel memory hotplug issue",
    "kernel CPU hotplug issue",
    "kernel node hotplug issue",
    "kernel device hotplug issue",
    "kernel udev issue",
    "kernel systemd issue",
    "kernel init issue",
    "kernel PID namespace issue",
    "kernel mount namespace issue",
    "kernel network namespace issue",
    "kernel user namespace issue",
    "kernel cgroup v2 issue",
    "kernel resource limit issue",
    "kernel rlimit issue",
    "kernel prlimit issue",
    "kernel signal mask issue",
    "kernel signal delivery issue",
    "kernel signal handling race",
    "kernel timer race",
    "kernel workqueue issue",
    "kernel tasklet issue",
    "kernel softirq issue",
    "kernel hardirq issue",
    "kernel IRQ balance issue",
    "kernel interrupt sharing issue",
    "kernel MSI issue",
    "kernel MSI-X issue",
    "kernel PCIe issue",
    "kernel USB 3.0 issue",
    "kernel Thunderbolt issue",
    "kernel NVMe issue",
    "kernel SSD issue",
    "kernel RAID issue",
    "kernel LVM issue",
    "kernel dm-crypt issue",
    "kernel LUKS issue",
    "kernel network bonding issue",
    "kernel network teaming issue",
    "kernel network bridging issue",
    "kernel VLAN issue",
    "kernel GRE tunnel issue",
    "kernel VXLAN issue",
    "kernel WireGuard issue",
    "kernel IPsec issue",
    "kernel TCP congestion control",
    "kernel TCP window issue",
    "kernel TCP retransmission issue",
    "kernel TCP segmentation offload",
    "kernel UDP checksum issue",
    "kernel ICMP issue",
    "kernel ARP issue",
    "kernel DNS issue",
    "kernel DHCP issue",
    "kernel NTP issue",
    "kernel PTP issue",
    "kernel time synchronization issue",
    "kernel RTC issue",
    "kernel clock source issue",
    "kernel TSC issue",
    "kernel HPET issue",
    "kernel ACPI timer issue",
    "kernel watchdog issue",
    "kernel panic watchdog",
    "kernel NMI watchdog",
    "kernel soft lockup watchdog",
    "kernel hard lockup watchdog",
    "kernel temperature watchdog",
    "kernel thermal throttling",
    "kernel CPU frequency issue",
    "kernel CPU governor issue",
    "kernel power saving issue",
    "kernel suspend to RAM issue",
    "kernel suspend to disk issue",
    "kernel hibernation resume issue",
    "kernel firmware loading issue",
    "kernel EFI runtime service issue",
    "kernel UEFI secure boot issue",
    "kernel module signing issue",
    "kernel keyring issue",
    "kernel crypto issue",
    "kernel random number generator issue",
    "kernel entropy issue",
    "kernel DRNG issue",
    "kernel RDRAND issue",
    "kernel RDSEED issue",
    "kernel SHA issue",
    "kernel AES issue",
    "kernel RSA issue",
    "kernel ECC issue",
    "kernel TLS issue",
    "kernel SSL issue",
    "kernel HTTPS issue",
    "kernel QUIC issue",
    "kernel HTTP/2 issue",
    "kernel HTTP/3 issue",
    "kernel WebSocket issue",
    "kernel gRPC issue",
    "kernel REST API issue",
    "kernel JSON-RPC issue",
    "kernel XML-RPC issue",
    "kernel SOAP issue",
    "kernel CORBA issue",
    "kernel D-Bus issue",
    "kernel System V IPC issue",
    "kernel POSIX IPC issue",
    "kernel shared memory issue",
    "kernel semaphore issue",
    "kernel message queue issue",
    "kernel FIFO issue",
    "kernel pipe issue",
    "kernel socketpair issue",
    "kernel eventfd issue",
    "kernel timerfd issue",
    "kernel signalfd issue",
    "kernel inotify issue",
    "kernel fanotify issue",
    "kernel dnotify issue",
    "kernel epoll issue",
    "kernel kqueue issue",
    "kernel poll issue",
    "kernel select issue",
    "kernel I/O multiplexing issue",
    "kernel asynchronous I/O issue",
    "kernel AIO issue",
    "kernel io_uring issue",
    "kernel splice issue",
    "kernel vmsplice issue",
    "kernel tee issue",
    "kernel copy_file_range issue",
    "kernel sendfile issue",
    "kernel zero copy issue",
    "kernel page cache issue",
    "kernel dentry cache issue",
    "kernel inode cache issue",
    "kernel buffer cache issue",
    "kernel slab cache issue",
    "kernel kmem_cache issue",
    "kernel SLUB issue",
    "kernel SLAB issue",
    "kernel SLOB issue",
    "kernel memory allocation issue",
    "kernel kmalloc issue",
    "kernel vmalloc issue",
    "kernel kmap issue",
    "kernel vmap issue",
    "kernel get_free_page issue",
    "kernel alloc_pages issue",
    "kernel page allocation failure",
    "kernel GFP flags issue",
    "kernel __GFP_ATOMIC issue",
    "kernel __GFP_NOWAIT issue",
    "kernel __GFP_WAIT issue",
    "kernel __GFP_IO issue",
    "kernel __GFP_FS issue",
    "kernel __GFP_NOFAIL issue",
    "kernel memory leak detection",
    "kernel kmemleak",
    "kernel slab leak",
    "kernel page leak",
    "kernel reference count leak",
    "kernel RCU leak",
    "kernel spinlock leak",
    "kernel mutex leak",
    "kernel semaphore leak",
    "kernel rwlock leak",
    "kernel file descriptor leak",
    "kernel socket leak",
    "kernel process leak",
    "kernel thread leak",
    "kernel workqueue leak",
    "kernel tasklet leak",
    "kernel softirq leak",
    "kernel hardirq leak",
    "kernel timer leak",
    "kernel kthread leak",
    "kernel waitqueue leak",
    "kernel completion leak",
    "kernel barrier leak",
    "kernel seqlock leak",
    "kernel rwsem leak",
    "kernel percpu leak",
    "kernel stack overflow",
    "kernel stack corruption",
    "kernel heap corruption",
    "kernel data corruption",
    "kernel code corruption",
    "kernel instruction corruption",
    "kernel cache corruption",
    "kernel TLB corruption",
    "kernel page table corruption",
    "kernel mmu corruption",
    "kernel memory corruption detection",
    "kernel KASAN",
    "kernel KMSAN",
    "kernel KCSAN",
    "kernel KFENCE",
    "kernel KCOV",
    "kernel kmemcheck",
    "kernel lockdep",
    "kernel lockstat",
    "kernel mutex debug",
    "kernel spinlock debug",
    "kernel RCU debug",
    "kernel deadlock debug",
    "kernel livelock debug",
    "kernel race condition debug",
    "kernel concurrency debug",
    "kernel atomic operation debug",
    "kernel memory barrier debug",
    "kernel smp barrier debug",
    "kernel cache coherence debug",
    "kernel MESI protocol issue",
    "kernel MOESI protocol issue",
    "kernel MESIF protocol issue",
    "kernel MSI protocol issue",
    "kernel directory protocol issue",
    "kernel cache protocol issue",
    "kernel memory protocol issue",
    "kernel bus protocol issue",
    "kernel PCI protocol issue",
    "kernel USB protocol issue",
    "kernel SATA protocol issue",
    "kernel SAS protocol issue",
    "kernel NVMe protocol issue",
    "kernel Ethernet protocol issue",
    "kernel TCP protocol issue",
    "kernel IP protocol issue",
    "kernel UDP protocol issue",
    "kernel ICMP protocol issue",
    "kernel ARP protocol issue",
    "kernel DNS protocol issue",
    "kernel DHCP protocol issue",
    "kernel NTP protocol issue",
    "kernel PTP protocol issue",
    "kernel SCTP protocol issue",
    "kernel DCCP protocol issue",
    "kernel RTP protocol issue",
    "kernel RTCP protocol issue",
    "kernel QUIC protocol issue",
    "kernel HTTP protocol issue",
    "kernel HTTPS protocol issue",
    "kernel WebSocket protocol issue",
    "kernel gRPC protocol issue",
    "kernel REST API protocol issue",
    "kernel JSON-RPC protocol issue",
    "kernel XML-RPC protocol issue",
    "kernel SOAP protocol issue",
    "kernel CORBA protocol issue",
    "kernel D-Bus protocol issue",
    "kernel System V IPC protocol issue",
    "kernel POSIX IPC protocol issue",
    "kernel shared memory protocol issue",
    "kernel semaphore protocol issue",
    "kernel message queue protocol issue",
    "kernel FIFO protocol issue",
    "kernel pipe protocol issue",
    "kernel socketpair protocol issue",
    "kernel eventfd protocol issue",
    "kernel timerfd protocol issue",
    "kernel signalfd protocol issue",
    "kernel inotify protocol issue",
    "kernel fanotify protocol issue",
    "kernel dnotify protocol issue",
    "kernel epoll protocol issue",
    "kernel kqueue protocol issue",
    "kernel poll protocol issue",
    "kernel select protocol issue",
    "kernel I/O multiplexing protocol issue",
    "kernel asynchronous I/O protocol issue",
    "kernel AIO protocol issue",
    "kernel io_uring protocol issue",
    "kernel splice protocol issue",
    "kernel vmsplice protocol issue",
    "kernel tee protocol issue",
    "kernel copy_file_range protocol issue",
    "kernel sendfile protocol issue",
    "kernel zero copy protocol issue",
    "kernel page cache protocol issue",
    "kernel dentry cache protocol issue",
    "kernel inode cache protocol issue",
    "kernel buffer cache protocol issue",
    "kernel slab cache protocol issue",
    "kernel kmem_cache protocol issue",
    "kernel SLUB protocol issue",
    "kernel SLAB protocol issue",
    "kernel SLOB protocol issue",
    "kernel memory allocation protocol issue",
    "kernel kmalloc protocol issue",
    "kernel vmalloc protocol issue",
    "kernel kmap protocol issue",
    "kernel vmap protocol issue",
    "kernel get_free_page protocol issue",
    "kernel alloc_pages protocol issue",
    "kernel page allocation failure protocol issue",
    "kernel GFP flags protocol issue",
    "kernel __GFP_ATOMIC protocol issue",
    "kernel __GFP_NOWAIT protocol issue",
    "kernel __GFP_WAIT protocol issue",
    "kernel __GFP_IO protocol issue",
    "kernel __GFP_FS protocol issue",
    "kernel __GFP_NOFAIL protocol issue",
    "kernel memory leak detection protocol issue",
    "kernel kmemleak protocol issue",
    "kernel slab leak protocol issue",
    "kernel page leak protocol issue",
    "kernel reference count leak protocol issue",
    "kernel RCU leak protocol issue",
    "kernel spinlock leak protocol issue",
    "kernel mutex leak protocol issue",
    "kernel semaphore leak protocol issue",
    "kernel rwlock leak protocol issue",
    "kernel file descriptor leak protocol issue",
    "kernel socket leak protocol issue",
    "kernel process leak protocol issue",
    "kernel thread leak protocol issue",
    "kernel workqueue leak protocol issue",
    "kernel tasklet leak protocol issue",
    "kernel softirq leak protocol issue",
    "kernel hardirq leak protocol issue",
    "kernel timer leak protocol issue",
    "kernel kthread leak protocol issue",
    "kernel waitqueue leak protocol issue",
    "kernel completion leak protocol issue",
    "kernel barrier leak protocol issue",
    "kernel seqlock leak protocol issue",
    "kernel rwsem leak protocol issue",
    "kernel percpu leak protocol issue",
    "kernel stack overflow protocol issue",
    "kernel stack corruption protocol issue",
    "kernel heap corruption protocol issue",
    "kernel data corruption protocol issue",
    "kernel code corruption protocol issue",
    "kernel instruction corruption protocol issue",
    "kernel cache corruption protocol issue",
    "kernel TLB corruption protocol issue",
    "kernel page table corruption protocol issue",
    "kernel mmu corruption protocol issue",
    "kernel memory corruption detection protocol issue",
    "kernel KASAN protocol issue",
    "kernel KMSAN protocol issue",
    "kernel KCSAN protocol issue",
    "kernel KFENCE protocol issue",
    "kernel KCOV protocol issue",
    "kernel kmemcheck protocol issue",
    "kernel lockdep protocol issue",
    "kernel lockstat protocol issue",
    "kernel mutex debug protocol issue",
    "kernel spinlock debug protocol issue",
    "kernel RCU debug protocol issue",
    "kernel deadlock debug protocol issue",
    "kernel livelock debug protocol issue",
    "kernel race condition debug protocol issue",
    "kernel concurrency debug protocol issue",
    "kernel atomic operation debug protocol issue",
    "kernel memory barrier debug protocol issue",
    "kernel smp barrier debug protocol issue",
    "kernel cache coherence debug protocol issue"
]

def fetch_high_quality_cases(target_count: int = 1000) -> None:
    """
    Fetch high-quality kernel cases until target count is reached.
    """
    print(f"Starting to fetch {target_count} high-quality kernel cases...")
    
    # Initialize case acquisition
    acquisition = CaseAcquisition()
    
    # Track progress
    total_processed = 0
    successful_count = 0
    failed_count = 0
    duplicate_count = 0
    
    # Fetch cases in batches
    batch_size = 50  # cases per keyword per source
    max_retries = 3  # max retries for each keyword
    
    # Get initial count of cases
    initial_cases = KernelCase.objects.count()
    print(f"Initial cases in database: {initial_cases}")
    
    # Loop through keywords until we reach target
    for keyword in extended_keywords:
        # Skip if we've reached target
        if successful_count >= target_count:
            break
            
        print(f"\nProcessing keyword: {keyword}")
        
        for retry in range(max_retries):
            try:
                # Fetch cases for this keyword
                results = acquisition.run(
                    keywords=[keyword],
                    max_per_keyword=batch_size,
                    sources=["stackoverflow", "csdn", "zhihu", "juejin"]
                )
                
                # Update counts
                total_processed += len(results)
                
                # Count results by type
                batch_successful = 0
                batch_duplicate = 0
                batch_failed = 0
                
                for result in results:
                    if result.get("success"):
                        batch_successful += 1
                        successful_count += 1
                    elif "Duplicate case found" in result.get("message", ""):
                        batch_duplicate += 1
                        duplicate_count += 1
                    else:
                        batch_failed += 1
                        failed_count += 1
                
                print(f"  Keyword '{keyword}' (retry {retry+1}/{max_retries}):")
                print(f"    Processed: {len(results)} cases")
                print(f"    Successful: {batch_successful} cases")
                print(f"    Duplicates: {batch_duplicate} cases")
                print(f"    Failed: {batch_failed} cases")
                print(f"    Total successful: {successful_count}/{target_count}")
                
                # Break retry loop if we got some results
                if batch_successful > 0:
                    break
                    
            except Exception as e:
                print(f"  Error processing keyword '{keyword}': {e}")
                time.sleep(2)  # Wait before retry
        
        # Wait between keywords to avoid rate limits
        time.sleep(1)
    
    # Final summary
    print(f"\n{'='*60}")
    print("Fetching complete!")
    print(f"Total processed: {total_processed}")
    print(f"Successful: {successful_count}")
    print(f"Duplicates: {duplicate_count}")
    print(f"Failed: {failed_count}")
    print(f"Final cases in database: {KernelCase.objects.count()}")
    print(f"New cases added: {KernelCase.objects.count() - initial_cases}")
    print(f"{'='*60}")

if __name__ == "__main__":
    fetch_high_quality_cases(1000)