# Generated by Django 4.2.28 on 2026-03-03 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KernelCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=50, unique=True, verbose_name='案例ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('symptoms', models.TextField(verbose_name='症状')),
                ('root_cause', models.TextField(verbose_name='根本原因')),
                ('solution', models.TextField(verbose_name='解决方案')),
                ('kernel_version', models.CharField(max_length=50, verbose_name='内核版本')),
                ('affected_components', models.CharField(max_length=200, verbose_name='影响组件')),
                ('severity', models.CharField(choices=[('Low', '低'), ('Medium', '中'), ('High', '高'), ('Critical', '严重')], max_length=20, verbose_name='严重程度')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '内核问题案例',
                'verbose_name_plural': '内核问题案例',
                'ordering': ['-created_date'],
            },
        ),
    ]
