# Generated by Django 4.2.29 on 2026-03-06 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kernelcase',
            options={'ordering': ['-created_date'], 'verbose_name': 'Kernel Issue Case', 'verbose_name_plural': 'Kernel Issue Cases'},
        ),
        migrations.AddField(
            model_name='kernelcase',
            name='answers_count',
            field=models.IntegerField(default=0, verbose_name='Answers Count'),
        ),
        migrations.AddField(
            model_name='kernelcase',
            name='conclusion',
            field=models.TextField(blank=True, default='', verbose_name='Conclusion'),
        ),
        migrations.AddField(
            model_name='kernelcase',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Content Hash'),
        ),
        migrations.AddField(
            model_name='kernelcase',
            name='module',
            field=models.CharField(blank=True, choices=[('memory', 'Memory Management'), ('network', 'Network'), ('scheduler', 'Scheduler'), ('lock', 'Lock/Synchronization'), ('timer', 'Timer'), ('storage', 'Storage/Filesystem'), ('irq', 'Interrupt'), ('driver', 'Device Driver'), ('other', 'Other')], default='other', max_length=50, verbose_name='Kernel Module'),
        ),
        migrations.AddField(
            model_name='kernelcase',
            name='problem_analysis',
            field=models.TextField(blank=True, default='', verbose_name='Problem Analysis'),
        ),
        migrations.AddField(
            model_name='kernelcase',
            name='source',
            field=models.CharField(blank=True, default='', help_text='e.g. stackoverflow, csdn, zhihu', max_length=50, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='kernelcase',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Source ID'),
        ),
        migrations.AddField(
            model_name='kernelcase',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='kernelcase',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='Original URL'),
        ),
        migrations.AddField(
            model_name='kernelcase',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Votes'),
        ),
        migrations.AlterField(
            model_name='kernelcase',
            name='affected_components',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Affected Components'),
        ),
        migrations.AlterField(
            model_name='kernelcase',
            name='case_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='kernelcase',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='kernelcase',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='kernelcase',
            name='kernel_version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Kernel Version'),
        ),
        migrations.AlterField(
            model_name='kernelcase',
            name='root_cause',
            field=models.TextField(verbose_name='Root Cause'),
        ),
        migrations.AlterField(
            model_name='kernelcase',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20, verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='kernelcase',
            name='solution',
            field=models.TextField(verbose_name='Solution'),
        ),
        migrations.AlterField(
            model_name='kernelcase',
            name='symptoms',
            field=models.TextField(verbose_name='Symptoms'),
        ),
        migrations.AlterField(
            model_name='kernelcase',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='kernelcase',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
