# Generated by Django 4.2.11 on 2026-03-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_kernelcase_options_kernelcase_answers_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kernelcase',
            name='embedding',
            field=models.JSONField(blank=True, default=list, help_text='Vector representation for RAG', verbose_name='Embedding'),
        ),
    ]
