# Generated by Django 4.2.11 on 2026-03-09 01:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_kernelcase_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawCase',
            fields=[
                ('raw_id', models.AutoField(primary_key=True, serialize=False, verbose_name='原始案例ID')),
                ('source', models.CharField(choices=[('stackoverflow', 'StackOverflow'), ('csdn', 'CSDN'), ('zhihu', '知乎'), ('juejin', '掘金'), ('other', '其他')], max_length=50, verbose_name='数据源')),
                ('source_id', models.CharField(blank=True, default='', max_length=100, verbose_name='源ID')),
                ('url', models.URLField(blank=True, default='', max_length=500, verbose_name='原始URL')),
                ('raw_title', models.CharField(blank=True, default='', max_length=500, verbose_name='原始标题')),
                ('raw_content', models.TextField(verbose_name='原始内容')),
                ('raw_html', models.TextField(blank=True, default='', verbose_name='原始HTML')),
                ('fetch_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='获取时间')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('processed', '已处理'), ('failed', '处理失败'), ('low_quality', '质量不合格')], default='pending', max_length=20, verbose_name='处理状态')),
                ('process_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('process_error', models.TextField(blank=True, default='', verbose_name='处理错误信息')),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='内容哈希')),
            ],
            options={
                'verbose_name': '原始案例',
                'verbose_name_plural': '原始案例',
                'db_table': 'raw_cases',
                'ordering': ['-fetch_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='kernelcase',
            options={'ordering': ['-created_date'], 'verbose_name': 'Kernel Issue Case (Legacy)', 'verbose_name_plural': 'Kernel Issue Cases (Legacy)'},
        ),
        migrations.AlterModelTable(
            name='kernelcase',
            table='kernel_cases',
        ),
        migrations.CreateModel(
            name='TrainingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='案例ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('phenomenon', models.TextField(verbose_name='问题现象')),
                ('key_logs', models.TextField(blank=True, default='', verbose_name='关键日志')),
                ('environment', models.TextField(blank=True, default='', verbose_name='环境信息')),
                ('root_cause', models.TextField(verbose_name='根本原因')),
                ('analysis_process', models.TextField(blank=True, default='', verbose_name='分析过程')),
                ('troubleshooting_steps', models.JSONField(blank=True, default=list, verbose_name='排查步骤')),
                ('solution', models.TextField(verbose_name='解决方案')),
                ('prevention', models.TextField(blank=True, default='', verbose_name='预防措施')),
                ('kernel_version', models.CharField(blank=True, default='', max_length=50, verbose_name='内核版本')),
                ('affected_components', models.CharField(blank=True, default='', max_length=200, verbose_name='受影响组件')),
                ('module', models.CharField(choices=[('memory', '内存管理'), ('network', '网络'), ('scheduler', '调度器'), ('lock', '锁/同步'), ('timer', '定时器'), ('storage', '存储/文件系统'), ('irq', '中断'), ('driver', '设备驱动'), ('other', '其他')], default='other', max_length=50, verbose_name='内核模块')),
                ('severity', models.CharField(choices=[('Low', '低'), ('Medium', '中'), ('High', '高'), ('Critical', '严重')], default='Medium', max_length=20, verbose_name='严重程度')),
                ('source', models.CharField(blank=True, default='', max_length=50, verbose_name='数据源')),
                ('source_id', models.CharField(blank=True, default='', max_length=100, verbose_name='源ID')),
                ('url', models.URLField(blank=True, default='', max_length=500, verbose_name='原始URL')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('votes', models.IntegerField(default=0, verbose_name='投票数')),
                ('answers_count', models.IntegerField(default=0, verbose_name='回答数')),
                ('quality_score', models.FloatField(default=0.0, verbose_name='质量分数')),
                ('confidence', models.FloatField(default=0.0, verbose_name='置信度')),
                ('embedding', models.JSONField(blank=True, default=list, help_text='用于RAG的向量表示', verbose_name='向量嵌入')),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='内容哈希')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('raw_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_cases', to='cases.rawcase', verbose_name='原始案例')),
            ],
            options={
                'verbose_name': '训练案例',
                'verbose_name_plural': '训练案例',
                'db_table': 'training_cases',
                'ordering': ['-quality_score', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='案例ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('phenomenon', models.TextField(verbose_name='问题现象')),
                ('key_logs', models.TextField(blank=True, default='', verbose_name='关键日志')),
                ('environment', models.TextField(blank=True, default='', verbose_name='环境信息')),
                ('root_cause', models.TextField(verbose_name='根本原因')),
                ('analysis_process', models.TextField(blank=True, default='', verbose_name='分析过程')),
                ('troubleshooting_steps', models.JSONField(blank=True, default=list, verbose_name='排查步骤')),
                ('solution', models.TextField(verbose_name='解决方案')),
                ('prevention', models.TextField(blank=True, default='', verbose_name='预防措施')),
                ('kernel_version', models.CharField(blank=True, default='', max_length=50, verbose_name='内核版本')),
                ('affected_components', models.CharField(blank=True, default='', max_length=200, verbose_name='受影响组件')),
                ('module', models.CharField(choices=[('memory', '内存管理'), ('network', '网络'), ('scheduler', '调度器'), ('lock', '锁/同步'), ('timer', '定时器'), ('storage', '存储/文件系统'), ('irq', '中断'), ('driver', '设备驱动'), ('other', '其他')], default='other', max_length=50, verbose_name='内核模块')),
                ('severity', models.CharField(choices=[('Low', '低'), ('Medium', '中'), ('High', '高'), ('Critical', '严重')], default='Medium', max_length=20, verbose_name='严重程度')),
                ('source', models.CharField(blank=True, default='', max_length=50, verbose_name='数据源')),
                ('source_id', models.CharField(blank=True, default='', max_length=100, verbose_name='源ID')),
                ('url', models.URLField(blank=True, default='', max_length=500, verbose_name='原始URL')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('votes', models.IntegerField(default=0, verbose_name='投票数')),
                ('answers_count', models.IntegerField(default=0, verbose_name='回答数')),
                ('quality_score', models.FloatField(default=0.0, verbose_name='质量分数')),
                ('confidence', models.FloatField(default=0.0, verbose_name='置信度')),
                ('embedding', models.JSONField(blank=True, default=list, help_text='用于RAG的向量表示', verbose_name='向量嵌入')),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='内容哈希')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('raw_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='cases.rawcase', verbose_name='原始案例')),
            ],
            options={
                'verbose_name': '测试案例',
                'verbose_name_plural': '测试案例',
                'db_table': 'test_cases',
                'ordering': ['-quality_score', '-created_date'],
            },
        ),
        migrations.AddIndex(
            model_name='rawcase',
            index=models.Index(fields=['source', 'status'], name='raw_cases_source_79981f_idx'),
        ),
        migrations.AddIndex(
            model_name='rawcase',
            index=models.Index(fields=['status'], name='raw_cases_status_17a464_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcase',
            index=models.Index(fields=['module', 'severity'], name='training_ca_module_4320ec_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcase',
            index=models.Index(fields=['quality_score'], name='training_ca_quality_c8f603_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['module', 'severity'], name='test_cases_module_c2727a_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['quality_score'], name='test_cases_quality_6e7485_idx'),
        ),
    ]
